/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.SkinnedMesh;
    Plane: THREE.SkinnedMesh;
    Sphere: THREE.SkinnedMesh;
    Sphere001: THREE.SkinnedMesh;
    Bone: THREE.Bone;
  };
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
  };
};

// type ActionName = 'Armature|Armature|ArmatureAction|Armature|ArmatureAction';
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function MushroomBoi(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials, animations } = useGLTF('/mushroom-boi.glb') as GLTFResult;
  const { actions } = useAnimations<THREE.AnimationClip>(animations, group);

  useEffect(() => {
    actions?.Idle?.play();
  }, [actions?.Idle]);

  return (
    <group ref={group} {...props} dispose={null}>
      <pointLight intensity={1.2} color="#38e4ed" />
      <group name="Armature" position={[0, -1, 0]}>
        <primitive object={nodes.Bone} />
        <skinnedMesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.008']}
          skeleton={nodes.Cylinder.skeleton}
        />
        <skinnedMesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials['Material.007']}
          skeleton={nodes.Plane.skeleton}
        />
        <skinnedMesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials['Material.006']}
          skeleton={nodes.Sphere.skeleton}
        />
        <skinnedMesh
          name="Sphere001"
          geometry={nodes.Sphere001.geometry}
          material={materials['Material.005']}
          skeleton={nodes.Sphere001.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/mushroom-boi.glb');
