/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Tree12003: THREE.Mesh;
    Tree_Type3_03_mesh003: THREE.Mesh;
    Tree9__1_: THREE.Mesh;
    Tree_Type4_01_mesh001: THREE.Mesh;
    Tree9001: THREE.Mesh;
    Tree_Type4_01_mesh_1: THREE.Mesh;
    Tree1: THREE.Mesh;
    Tree_Type5_04_mesh: THREE.Mesh;
    Tree2: THREE.Mesh;
    Tree_Type5_03_mesh: THREE.Mesh;
    Tree4: THREE.Mesh;
    Tree_Type5_01_mesh: THREE.Mesh;
    Tree3: THREE.Mesh;
    Tree_Type5_02_mesh: THREE.Mesh;
    Tree12: THREE.Mesh;
    Tree_Type3_03_mesh: THREE.Mesh;
    Tree10: THREE.Mesh;
    Tree_Type3_05_mesh: THREE.Mesh;
    Tree12004: THREE.Mesh;
    Tree_Type3_03_mesh004: THREE.Mesh;
    Tree5: THREE.Mesh;
    Tree_Type4_05_mesh: THREE.Mesh;
    Tree8: THREE.Mesh;
    Tree_Type4_02_mesh: THREE.Mesh;
    Tree12001: THREE.Mesh;
    Tree_Type3_03_mesh001: THREE.Mesh;
    Tree6: THREE.Mesh;
    Tree_Type4_04_mesh: THREE.Mesh;
    Tree7: THREE.Mesh;
    Tree_Type4_03_mesh: THREE.Mesh;
    Tree9: THREE.Mesh;
    Tree_Type4_01_mesh: THREE.Mesh;
    Tree13: THREE.Mesh;
    Tree_Type3_02_mesh: THREE.Mesh;
    Tree14: THREE.Mesh;
    Tree_Type3_01_mesh: THREE.Mesh;
    Bush: THREE.Mesh;
    Bush001: THREE.Mesh;
    Bush002: THREE.Mesh;
    Bush003: THREE.Mesh;
    Bush2: THREE.Mesh;
    Bush2001: THREE.Mesh;
    Scene068: THREE.Mesh;
    Scene068_1: THREE.Mesh;
    Scene052: THREE.Mesh;
    Scene052_1: THREE.Mesh;
    Scene048: THREE.Mesh;
    Scene048_1: THREE.Mesh;
    Scene064: THREE.Mesh;
    Scene064_1: THREE.Mesh;
    Scene051: THREE.Mesh;
    Scene051_1: THREE.Mesh;
    Scene055: THREE.Mesh;
    Scene055_1: THREE.Mesh;
    Scene067: THREE.Mesh;
    Scene067_1: THREE.Mesh;
    Scene063: THREE.Mesh;
    Scene063_1: THREE.Mesh;
    Scene061: THREE.Mesh;
    Scene061_1: THREE.Mesh;
    Scene059: THREE.Mesh;
    Scene059_1: THREE.Mesh;
    Scene057: THREE.Mesh;
    Scene057_1: THREE.Mesh;
    Window003: THREE.Mesh;
    Tower009: THREE.Mesh;
    Tower010: THREE.Mesh;
    Tower011: THREE.Mesh;
    Plant_Holder_1010: THREE.Mesh;
    Plant_Holder_1011: THREE.Mesh;
    Plant_Holder_1012: THREE.Mesh;
    Roundcube093: THREE.Mesh;
    Roundcube094: THREE.Mesh;
    Roundcube095: THREE.Mesh;
    Roundcube096: THREE.Mesh;
    Roundcube097: THREE.Mesh;
    Roundcube098: THREE.Mesh;
    Roundcube099: THREE.Mesh;
    Roundcube100: THREE.Mesh;
    Roundcube101: THREE.Mesh;
    Roundcube102: THREE.Mesh;
    Roundcube103: THREE.Mesh;
    Roundcube104: THREE.Mesh;
    Roundcube105: THREE.Mesh;
    Roundcube106: THREE.Mesh;
    Roundcube107: THREE.Mesh;
    Roundcube108: THREE.Mesh;
    Roundcube109: THREE.Mesh;
    Roundcube110: THREE.Mesh;
    Roundcube111: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Roundcube: THREE.Mesh;
    Roundcube007: THREE.Mesh;
    Tower003: THREE.Mesh;
    Plant_Holder_1001: THREE.Mesh;
    Plant_Holder_1002: THREE.Mesh;
    Plant_Holder_1003: THREE.Mesh;
    Roundcube002: THREE.Mesh;
    Roundcube002_1: THREE.Mesh;
    Roundcube045: THREE.Mesh;
    Roundcube046: THREE.Mesh;
    Roundcube047: THREE.Mesh;
    Roundcube048: THREE.Mesh;
    Roundcube049: THREE.Mesh;
    Roundcube050: THREE.Mesh;
    Roundcube051: THREE.Mesh;
    Roundcube052: THREE.Mesh;
    Roundcube059_1: THREE.Mesh;
    Roundcube059_2: THREE.Mesh;
    Window001: THREE.Mesh;
    Door_L002: THREE.Mesh;
    Roundcube058: THREE.Mesh;
    Roundcube059: THREE.Mesh;
    Door_R002: THREE.Mesh;
    Door_R003: THREE.Mesh;
    Door_L003: THREE.Mesh;
    Tower004: THREE.Mesh;
    Tower005: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane019: THREE.Mesh;
    Plane020: THREE.Mesh;
    Plane021: THREE.Mesh;
    Plane022: THREE.Mesh;
    Window002: THREE.Mesh;
    Tower006: THREE.Mesh;
    Tower007: THREE.Mesh;
    Tower008: THREE.Mesh;
    Plant_Holder_1007: THREE.Mesh;
    Plant_Holder_1008: THREE.Mesh;
    Plant_Holder_1009: THREE.Mesh;
    Roundcube062: THREE.Mesh;
    Roundcube063: THREE.Mesh;
    Roundcube064: THREE.Mesh;
    Roundcube065: THREE.Mesh;
    Roundcube066: THREE.Mesh;
    Roundcube067: THREE.Mesh;
    Roundcube068: THREE.Mesh;
    Roundcube069: THREE.Mesh;
    Roundcube070: THREE.Mesh;
    Roundcube071: THREE.Mesh;
    Roundcube072: THREE.Mesh;
    Roundcube073: THREE.Mesh;
    Roundcube074: THREE.Mesh;
    Roundcube075: THREE.Mesh;
    Roundcube076: THREE.Mesh;
    Roundcube077: THREE.Mesh;
    Roundcube078: THREE.Mesh;
    Roundcube079: THREE.Mesh;
    Roundcube080: THREE.Mesh;
    Roundcube081: THREE.Mesh;
    Roundcube082: THREE.Mesh;
    Roundcube083: THREE.Mesh;
    Roundcube084: THREE.Mesh;
    Roundcube085: THREE.Mesh;
    Plane023: THREE.Mesh;
    Plane024: THREE.Mesh;
    Plane025: THREE.Mesh;
    Plane026: THREE.Mesh;
    Plane027: THREE.Mesh;
    Plane028: THREE.Mesh;
    Plane029: THREE.Mesh;
    Plane030: THREE.Mesh;
    Plane031: THREE.Mesh;
    Plane032: THREE.Mesh;
    Plane033: THREE.Mesh;
    Door_R004: THREE.Mesh;
    Door_R005: THREE.Mesh;
    Door_L004: THREE.Mesh;
    Door_L005: THREE.Mesh;
    Roundcube060: THREE.Mesh;
    Roundcube061: THREE.Mesh;
    stone_01: THREE.Mesh;
    stone_02: THREE.Mesh;
    stone_02001: THREE.Mesh;
    stone_02002: THREE.Mesh;
    stone_03: THREE.Mesh;
    stone_04: THREE.Mesh;
    Roundcube041: THREE.Mesh;
    Roundcube041_1: THREE.Mesh;
    Roundcube010: THREE.Mesh;
    Roundcube010_1: THREE.Mesh;
    Roundcube011: THREE.Mesh;
    Roundcube011_1: THREE.Mesh;
    Roundcube012: THREE.Mesh;
    Roundcube012_1: THREE.Mesh;
    Roundcube013: THREE.Mesh;
    Roundcube013_1: THREE.Mesh;
    Roundcube015: THREE.Mesh;
    Roundcube015_1: THREE.Mesh;
    simple_tower: THREE.Mesh;
    Grass: THREE.Mesh;
    Grass2: THREE.Mesh;
    Grass3: THREE.Mesh;
    Grass4: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane034: THREE.Mesh;
  };
  materials: {
    _trees_normal: THREE.MeshStandardMaterial;
    _trees_normal_011: THREE.MeshStandardMaterial;
    ['Gradient Texture 2.002']: THREE.MeshStandardMaterial;
    ['Gradient Texture 2.001']: THREE.MeshStandardMaterial;
    ['Window Material.003']: THREE.MeshPhysicalMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Building Base Color.003']: THREE.MeshPhysicalMaterial;
    ['Gradient Texture 2.003']: THREE.MeshStandardMaterial;
    ['Gradient Texture.003']: THREE.MeshStandardMaterial;
    ['Window Material.001']: THREE.MeshPhysicalMaterial;
    Stone: THREE.MeshStandardMaterial;
    ['Building Base Color.001']: THREE.MeshPhysicalMaterial;
    Material: THREE.MeshStandardMaterial;
    ['Gradient Texture.001']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Building Base Color.002']: THREE.MeshPhysicalMaterial;
    ['Gradient Texture.002']: THREE.MeshStandardMaterial;
    ['Building Base Color']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['simple tower']: THREE.MeshStandardMaterial;
    Grass: THREE.MeshStandardMaterial;
    Grass2: THREE.MeshStandardMaterial;
    Grass3: THREE.MeshStandardMaterial;
    Grass4: THREE.MeshStandardMaterial;
    Leaves: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
  };
};

export function VibrantSceneExtra(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/ripple-demo-scene-v001-cleaned-12-22-22 v6.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} position={[30, -15.005, -40]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree12003.geometry}
        material={materials._trees_normal}
        position={[-1.97, 4.49, 30.99]}
        rotation={[Math.PI / 2, 0, 2.37]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_03_mesh003.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree9__1_.geometry}
        material={materials._trees_normal}
        position={[-4, 4.49, 29.92]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_01_mesh001.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree9001.geometry}
        material={materials._trees_normal}
        position={[77.17, 4.49, 29.91]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_01_mesh_1.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree1.geometry}
        material={materials._trees_normal}
        position={[13.83, 5.4, 48.77]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type5_04_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree2.geometry}
        material={materials._trees_normal}
        position={[24.63, 4.52, 49.49]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type5_03_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree4.geometry}
        material={materials._trees_normal}
        position={[4.42, 4.49, 30.49]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type5_01_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree3.geometry}
        material={materials._trees_normal}
        position={[61.92, 4.48, 29.31]}
        rotation={[Math.PI / 2, 0, -0.97]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type5_02_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree12.geometry}
        material={materials._trees_normal}
        position={[31.73, 4.44, 30.76]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_03_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree10.geometry}
        material={materials._trees_normal}
        position={[9.16, 4.48, 27.96]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_05_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree12004.geometry}
        material={materials._trees_normal}
        position={[18.8, 5.02, 28.62]}
        rotation={[Math.PI / 2, 0, 1.82]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_03_mesh004.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree5.geometry}
        material={materials._trees_normal}
        position={[-1.41, 4.54, 25.92]}
        rotation={[Math.PI / 2, 0, 0.69]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_05_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree8.geometry}
        material={materials._trees_normal}
        position={[-10.51, 4.48, 47.16]}
        rotation={[Math.PI / 2, 0, 1.31]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_02_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree12001.geometry}
        material={materials._trees_normal}
        position={[-3.44, 4.55, 51.05]}
        rotation={[Math.PI / 2, 0, -1.98]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_03_mesh001.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree6.geometry}
        material={materials._trees_normal}
        position={[7.36, 4.5, 50]}
        rotation={[Math.PI / 2, 0, -2.6]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_04_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree7.geometry}
        material={materials._trees_normal}
        position={[13.15, 4.5, 53]}
        rotation={[Math.PI / 2, 0, -1.22]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_03_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree9.geometry}
        material={materials._trees_normal}
        position={[3.61, 4.48, 47.13]}
        rotation={[Math.PI / 2, 0, -0.31]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type4_01_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree13.geometry}
        material={materials._trees_normal}
        position={[7.27, 4.53, 48.64]}
        rotation={[Math.PI / 2, 0, -1.85]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_02_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree14.geometry}
        material={materials._trees_normal}
        position={[17.48, 4.49, 47.78]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_Type3_01_mesh.geometry}
          material={materials._trees_normal_011}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[8.81, 4.86, 30.53]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush001.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[8.7, 4.73, 30.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush002.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[23.56, 4.85, 31.19]}
        rotation={[Math.PI / 2, 0, 3.13]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush003.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[23.98, 4.7, 31.03]}
        rotation={[Math.PI / 2, 0, 3.13]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush2.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[5.79, 4.49, 30.47]}
        rotation={[Math.PI / 2, 0, -0.15]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush2001.geometry}
        material={materials._trees_normal_011}
        position={[-2.42, 4.49, 29.23]}
        rotation={[Math.PI / 2, 0, 0.59]}
        scale={0.01}
      />
      <group position={[62.12, 4.48, 36]} rotation={[Math.PI / 2, 0, -0.97]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene068.geometry} material={materials._trees_normal} />
        <mesh castShadow receiveShadow geometry={nodes.Scene068_1.geometry} material={materials._trees_normal_011} />
      </group>
      <group position={[92.99, 4.53, 36.79]} rotation={[Math.PI / 2, 0, 0.69]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene052.geometry} material={materials._trees_normal} />
        <mesh castShadow receiveShadow geometry={nodes.Scene052_1.geometry} material={materials._trees_normal_011} />
      </group>
      <group position={[101.24, 4.45, 37.26]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene048.geometry} material={materials._trees_normal} />
        <mesh castShadow receiveShadow geometry={nodes.Scene048_1.geometry} material={materials._trees_normal_011} />
      </group>
      <group position={[70.42, 4.49, 36.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene064.geometry} material={materials._trees_normal} />
        <mesh castShadow receiveShadow geometry={nodes.Scene064_1.geometry} material={materials._trees_normal_011} />
      </group>
      <group position={[97.04, 4.54, 36.52]} rotation={[Math.PI / 2, 0, -1.98]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene051.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene051_1.geometry} material={materials._trees_normal} />
      </group>
      <group position={[88.76, 4.49, 36.96]} rotation={[Math.PI / 2, 0, 2.37]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene055.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene055_1.geometry} material={materials._trees_normal} />
      </group>
      <group position={[65.78, 4.49, 36.05]} rotation={[Math.PI / 2, 0, 1.82]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene067.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene067_1.geometry} material={materials._trees_normal} />
      </group>
      <group position={[74.68, 4.48, 36.21]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene063.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene063_1.geometry} material={materials._trees_normal} />
      </group>
      <group position={[77.92, 4.49, 36.38]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene061.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene061_1.geometry} material={materials._trees_normal} />
      </group>
      <group position={[81.23, 4.48, 36.54]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene059.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene059_1.geometry} material={materials._trees_normal} />
      </group>
      <group position={[84.86, 4.5, 36.76]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Scene057.geometry} material={materials._trees_normal_011} />
        <mesh castShadow receiveShadow geometry={nodes.Scene057_1.geometry} material={materials._trees_normal} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window003.geometry}
        material={materials['Window Material.003']}
        position={[-23.09, 42.79, -18.78]}
        rotation={[-Math.PI, 0.02, -Math.PI]}
        scale={[0.66, 0.75, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower009.geometry}
        material={materials['Material.004']}
        position={[-23.09, 42.69, -18.78]}
        rotation={[-Math.PI, 0.02, -Math.PI]}
        scale={0.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower010.geometry}
        material={materials['Material.004']}
        position={[-23.09, 41.34, -18.78]}
        rotation={[-Math.PI, 0.02, -Math.PI]}
        scale={0.67}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower011.geometry}
        material={materials['Building Base Color.003']}
        position={[-23.09, 41.34, -18.78]}
        rotation={[-Math.PI, 0.02, -Math.PI]}
        scale={0.67}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1010.geometry}
          material={materials['Material.004']}
          position={[-2.37, -3.65, -1.4]}
          rotation={[0, -0.56, 0]}
          scale={[1.96, 0.42, 1.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1011.geometry}
          material={materials['Material.004']}
          position={[2.4, -6.69, 0.03]}
          rotation={[0, -0.03, 0]}
          scale={[1.9, 0.41, 1.18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1012.geometry}
          material={materials['Material.004']}
          position={[-1.9, -10.15, 1.41]}
          rotation={[0, 0.66, 0]}
          scale={[1.94, 0.41, 1.21]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube093.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[2.79, -6.29, 0.05]}
          rotation={[0, -0.05, -0.84]}
          scale={[0.08, 0.39, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube094.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[2.72, -6.1, 0.04]}
          rotation={[0, -0.05, -0.45]}
          scale={[0.11, 0.57, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube095.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[2.53, -6.2, 0.17]}
          rotation={[0, -0.05, -0.2]}
          scale={[0.09, 0.43, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube096.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[1.67, -5.94, -0.24]}
          rotation={[0, -0.05, -0.12]}
          scale={[0.08, 0.39, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube097.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[1.49, -5.85, -0.25]}
          rotation={[0, -0.05, 0.27]}
          scale={[0.11, 0.57, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube098.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[1.42, -6.04, -0.12]}
          rotation={[0, -0.05, 0.52]}
          scale={[0.09, 0.43, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube099.geometry}
          material={materials['Gradient Texture.003']}
          position={[2.49, -6.43, -0.36]}
          rotation={[0, -0.05, 0]}
          scale={[0.68, 0.68, 1.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube100.geometry}
          material={materials['Gradient Texture.003']}
          position={[2.06, -6.39, 0.4]}
          rotation={[0, -0.05, 0]}
          scale={[0.61, 0.61, 0.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube101.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-2.11, -2.64, -0.97]}
          rotation={[3.14, 0.79, -2.7]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube102.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-2.02, -2.69, -0.88]}
          rotation={[3.14, 0.79, -2.42]}
          scale={[0.11, 0.57, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube103.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-2.08, -2.99, -0.94]}
          rotation={[3.14, 0.79, -2.14]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube104.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-2.57, -2.81, -1.43]}
          rotation={[0, -0.78, -0.46]}
          scale={[0.09, 0.38, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube105.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-2.64, -2.76, -1.49]}
          rotation={[0, -0.78, -0.18]}
          scale={[0.09, 0.43, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube106.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-2.73, -2.95, -1.59]}
          rotation={[0, -0.78, 0.1]}
          scale={[0.09, 0.38, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube107.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-3.14, -2.65, -1.98]}
          rotation={[0, -0.78, -0.08]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube108.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-3.23, -2.63, -2.08]}
          rotation={[0, -0.78, 0.21]}
          scale={[0.11, 0.57, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube109.geometry}
          material={materials['Gradient Texture 2.003']}
          position={[-3.28, -2.93, -2.13]}
          rotation={[0, -0.78, 0.49]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube110.geometry}
          material={materials['Gradient Texture.003']}
          position={[-2.06, -3.13, -1.3]}
          rotation={[0, -0.78, 0]}
          scale={1.2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube111.geometry}
          material={materials['Gradient Texture.003']}
          position={[-2.97, -3.33, -1.62]}
          rotation={[0, -0.78, 0]}
          scale={[0.77, 0.77, 0.32]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Building Base Color.003']}
        position={[109.64, 4.77, 0]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Window Material.001']}
        position={[109.64, 4.77, 0]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials['Building Base Color.003']}
        position={[7.16, 4.95, 51.69]}
        scale={0.46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials['Window Material.001']}
        position={[7.16, 4.95, 51.69]}
        scale={0.46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Building Base Color.003']}
        position={[24.07, 41.58, -16.2]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Window Material.001']}
        position={[24.07, 41.58, -16.2]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Building Base Color.003']}
        position={[29.39, 36.19, -16.25]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Window Material.001']}
        position={[29.39, 36.19, -16.25]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Building Base Color.003']}
        position={[40.61, 44.09, -50.11]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials['Window Material.001']}
        position={[40.61, 44.09, -50.11]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube.geometry}
        material={materials.Stone}
        position={[5.94, -3.08, -12.4]}
        scale={[16.33, 20.95, 11.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube007.geometry}
        material={materials.Stone}
        position={[27.24, -3.78, -25.77]}
        scale={[17.37, 22.28, 12.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower003.geometry}
        material={materials['Building Base Color.001']}
        position={[-9.18, 19.16, 49.75]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.95}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1001.geometry}
          material={materials.Material}
          position={[-1.9, -10.15, 1.41]}
          rotation={[0, 0.66, 0]}
          scale={[1.94, 0.41, 1.21]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1002.geometry}
          material={materials.Material}
          position={[2.4, -6.69, 0.03]}
          rotation={[0, -0.03, 0]}
          scale={[1.9, 0.41, 1.18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1003.geometry}
          material={materials.Material}
          position={[-2.37, -3.65, -1.4]}
          rotation={[0, -0.56, 0]}
          scale={[1.96, 0.42, 1.22]}
        />
        <group position={[-2.97, -3.33, -1.62]} rotation={[0, -0.78, 0]} scale={[0.77, 0.77, 0.32]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube002.geometry}
            material={materials['Gradient Texture.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube002_1.geometry}
            material={materials['Gradient Texture 2.001']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube045.geometry}
          material={materials['Gradient Texture.001']}
          position={[2.06, -6.39, 0.4]}
          rotation={[0, -0.05, 0]}
          scale={[0.61, 0.61, 0.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube046.geometry}
          material={materials['Gradient Texture.001']}
          position={[2.49, -6.43, -0.36]}
          rotation={[0, -0.05, 0]}
          scale={[0.68, 0.68, 1.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube047.geometry}
          material={materials['Gradient Texture 2.001']}
          position={[1.42, -6.04, -0.12]}
          rotation={[0, -0.05, 0.52]}
          scale={[0.09, 0.43, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube048.geometry}
          material={materials['Gradient Texture 2.001']}
          position={[1.49, -5.85, -0.25]}
          rotation={[0, -0.05, 0.27]}
          scale={[0.11, 0.57, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube049.geometry}
          material={materials['Gradient Texture 2.001']}
          position={[1.67, -5.94, -0.24]}
          rotation={[0, -0.05, -0.12]}
          scale={[0.08, 0.39, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube050.geometry}
          material={materials['Gradient Texture 2.001']}
          position={[2.53, -6.2, 0.17]}
          rotation={[0, -0.05, -0.2]}
          scale={[0.09, 0.43, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube051.geometry}
          material={materials['Gradient Texture 2.001']}
          position={[2.72, -6.1, 0.04]}
          rotation={[0, -0.05, -0.45]}
          scale={[0.11, 0.57, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube052.geometry}
          material={materials['Gradient Texture 2.001']}
          position={[2.79, -6.29, 0.05]}
          rotation={[0, -0.05, -0.84]}
          scale={[0.08, 0.39, 0.14]}
        />
        <group position={[-1.38, -9.56, 0.88]} rotation={[0, 0.29, -0.2]} scale={[0.1, 0.5, 0.11]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube059_1.geometry}
            material={materials['Gradient Texture 2.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roundcube059_2.geometry}
            material={materials['Gradient Texture.001']}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window001.geometry}
        material={materials['Window Material.001']}
        position={[-9.18, 21.23, 49.75]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={[0.94, 1.07, 0.94]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_L002.geometry}
        material={materials['Building Base Color.001']}
        position={[-9.13, 3.8, 49.82]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.85}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube058.geometry}
          material={materials.Material}
          position={[4.85, 2.19, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube059.geometry}
          material={materials.Material}
          position={[0.58, 1.96, 1.69]}
          scale={0.54}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_R002.geometry}
        material={materials['Building Base Color.001']}
        position={[-9.13, 3.8, 49.82]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_R003.geometry}
        material={materials.Material}
        position={[-9.13, 3.8, 49.81]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_L003.geometry}
        material={materials.Material}
        position={[-9.13, 3.8, 49.81]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower004.geometry}
        material={materials.Material}
        position={[-9.18, 19.16, 49.75]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower005.geometry}
        material={materials.Material}
        position={[-9.18, 21.1, 49.75]}
        rotation={[-Math.PI, 0.55, -Math.PI]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-12.83, 12.9, 48.48]}
        rotation={[1.66, -0.15, -2.64]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-7.06, 9.45, 48.25]}
        rotation={[1.5, -0.16, 2.71]}
        scale={[0.08, 0.08, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-5.62, 9.44, 47.9]}
        rotation={[1.6, -0.09, -2.51]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-10.26, 12.9, 47.32]}
        rotation={[1.76, -0.29, -2.21]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-11.25, 12.76, 46.77]}
        rotation={[1.57, -0.1, -2.95]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-6.79, 15.8, 50.83]}
        rotation={[1.84, -0.2, -1.84]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-6.55, 15.54, 51.84]}
        rotation={[1.74, -0.02, -1.71]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-7.65, 15.56, 50.41]}
        rotation={[1.67, -0.15, -2.55]}
        scale={[0.07, 0.07, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-11.58, 12.8, 50.15]}
        rotation={[1.54, 0.08, 0.67]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-7.17, 15.05, 52.72]}
        rotation={[1.54, 0.08, 0.67]}
        scale={[0.07, 0.07, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials['Gradient Texture 2.001']}
        position={[-6.91, 15.03, 52.73]}
        rotation={[1.54, 0.08, 0.67]}
        scale={[0.05, 0.05, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window002.geometry}
        material={materials['Window Material.001']}
        position={[28.53, 21.22, 29.91]}
        rotation={[0, -0.55, 0]}
        scale={[0.94, 1.07, 0.94]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower006.geometry}
        material={materials['Material.003']}
        position={[28.53, 21.09, 29.91]}
        rotation={[0, -0.55, 0]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower007.geometry}
        material={materials['Material.003']}
        position={[28.53, 19.15, 29.91]}
        rotation={[0, -0.55, 0]}
        scale={0.96}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower008.geometry}
        material={materials['Building Base Color.002']}
        position={[28.53, 19.15, 29.91]}
        rotation={[0, -0.55, 0]}
        scale={0.95}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1007.geometry}
          material={materials['Material.003']}
          position={[-2.37, -3.65, -1.4]}
          rotation={[0, -0.56, 0]}
          scale={[1.96, 0.42, 1.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1008.geometry}
          material={materials['Material.003']}
          position={[2.4, -6.69, 0.03]}
          rotation={[0, -0.03, 0]}
          scale={[1.9, 0.41, 1.18]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plant_Holder_1009.geometry}
          material={materials['Material.003']}
          position={[-1.9, -10.15, 1.41]}
          rotation={[0, 0.66, 0]}
          scale={[1.94, 0.41, 1.21]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube062.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-1.63, -9.51, 1.18]}
          rotation={[0, -0.02, 0.35]}
          scale={[0.09, 0.51, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube063.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-1.53, -9.27, 1.05]}
          rotation={[0, 0.29, 0.07]}
          scale={[0.14, 0.81, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube064.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-1.38, -9.56, 0.88]}
          rotation={[0, 0.29, -0.2]}
          scale={[0.1, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube065.geometry}
          material={materials['Gradient Texture.002']}
          position={[-0.96, -9.95, 0.94]}
          rotation={[0, 0.69, 0]}
          scale={1.13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube066.geometry}
          material={materials['Gradient Texture.002']}
          position={[-2.14, -9.89, 1.27]}
          rotation={[0, 0.69, 0]}
          scale={1.13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube067.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[2.79, -6.29, 0.05]}
          rotation={[0, -0.05, -0.84]}
          scale={[0.08, 0.39, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube068.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[2.72, -6.1, 0.04]}
          rotation={[0, -0.05, -0.45]}
          scale={[0.11, 0.57, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube069.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[2.53, -6.2, 0.17]}
          rotation={[0, -0.05, -0.2]}
          scale={[0.09, 0.43, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube070.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[1.67, -5.94, -0.24]}
          rotation={[0, -0.05, -0.12]}
          scale={[0.08, 0.39, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube071.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[1.49, -5.85, -0.25]}
          rotation={[0, -0.05, 0.27]}
          scale={[0.11, 0.57, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube072.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[1.42, -6.04, -0.12]}
          rotation={[0, -0.05, 0.52]}
          scale={[0.09, 0.43, 0.15]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube073.geometry}
          material={materials['Gradient Texture.002']}
          position={[2.49, -6.43, -0.36]}
          rotation={[0, -0.05, 0]}
          scale={[0.68, 0.68, 1.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube074.geometry}
          material={materials['Gradient Texture.002']}
          position={[2.06, -6.39, 0.4]}
          rotation={[0, -0.05, 0]}
          scale={[0.61, 0.61, 0.93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube075.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-2.11, -2.64, -0.97]}
          rotation={[3.14, 0.79, -2.7]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube076.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-2.02, -2.69, -0.88]}
          rotation={[3.14, 0.79, -2.42]}
          scale={[0.11, 0.57, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube077.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-2.08, -2.99, -0.94]}
          rotation={[3.14, 0.79, -2.14]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube078.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-2.57, -2.81, -1.43]}
          rotation={[0, -0.78, -0.46]}
          scale={[0.09, 0.38, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube079.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-2.64, -2.76, -1.49]}
          rotation={[0, -0.78, -0.18]}
          scale={[0.09, 0.43, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube080.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-2.73, -2.95, -1.59]}
          rotation={[0, -0.78, 0.1]}
          scale={[0.09, 0.38, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube081.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-3.14, -2.65, -1.98]}
          rotation={[0, -0.78, -0.08]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube082.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-3.23, -2.63, -2.08]}
          rotation={[0, -0.78, 0.21]}
          scale={[0.11, 0.57, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube083.geometry}
          material={materials['Gradient Texture 2.002']}
          position={[-3.28, -2.93, -2.13]}
          rotation={[0, -0.78, 0.49]}
          scale={[0.11, 0.5, 0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube084.geometry}
          material={materials['Gradient Texture.002']}
          position={[-2.06, -3.13, -1.3]}
          rotation={[0, -0.78, 0]}
          scale={1.2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube085.geometry}
          material={materials['Gradient Texture.002']}
          position={[-2.97, -3.33, -1.62]}
          rotation={[0, -0.78, 0]}
          scale={[0.77, 0.77, 0.32]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[26.26, 15.02, 26.92]}
        rotation={[1.6, -0.08, -2.47]}
        scale={[0.05, 0.05, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[26.52, 15.04, 26.93]}
        rotation={[1.6, -0.08, -2.47]}
        scale={[0.07, 0.07, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[30.93, 12.79, 29.51]}
        rotation={[1.6, -0.08, -2.47]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[27.01, 15.56, 29.24]}
        rotation={[1.47, 0.15, 0.59]}
        scale={[0.07, 0.07, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[25.9, 15.53, 27.82]}
        rotation={[1.4, 0.02, 1.44]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[26.15, 15.79, 28.82]}
        rotation={[1.3, 0.2, 1.3]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[30.61, 12.75, 32.89]}
        rotation={[1.57, 0.1, 0.2]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[29.61, 12.89, 32.34]}
        rotation={[1.38, 0.29, 0.93]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[24.97, 9.44, 31.76]}
        rotation={[1.54, 0.09, 0.63]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[26.42, 9.44, 31.41]}
        rotation={[1.64, 0.16, -0.43]}
        scale={[0.08, 0.08, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials['Gradient Texture 2.002']}
        position={[32.18, 12.89, 31.18]}
        rotation={[1.49, 0.15, 0.5]}
        scale={[0.09, 0.09, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_R004.geometry}
        material={materials['Material.003']}
        position={[28.48, 3.8, 29.85]}
        rotation={[0, -0.55, 0]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_R005.geometry}
        material={materials['Building Base Color.002']}
        position={[28.49, 3.8, 29.84]}
        rotation={[0, -0.55, 0]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_L004.geometry}
        material={materials['Material.003']}
        position={[28.48, 3.8, 29.85]}
        rotation={[0, -0.55, 0]}
        scale={0.85}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Door_L005.geometry}
        material={materials['Building Base Color.002']}
        position={[28.49, 3.8, 29.84]}
        rotation={[0, -0.55, 0]}
        scale={0.85}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube060.geometry}
          material={materials['Material.003']}
          position={[0.58, 1.96, 1.69]}
          scale={0.54}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube061.geometry}
          material={materials['Material.003']}
          position={[4.85, 2.19, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_01.geometry}
        material={materials.Stone}
        position={[17.55, 4.76, 29.27]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_02.geometry}
        material={materials.Stone}
        position={[4.81, 4.77, 46.81]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_02001.geometry}
        material={materials.Stone}
        position={[4.53, 4.78, 27.94]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_02002.geometry}
        material={materials.Stone}
        position={[-1.92, 4.56, 27.2]}
        rotation={[-2.15, -0.28, 3.11]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_03.geometry}
        material={materials.Stone}
        position={[5.06, 4.51, 22.67]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone_04.geometry}
        material={materials.Stone}
        position={[-4.34, 4.77, 47.16]}
        rotation={[Math.PI / 2, 0, -2.56]}
        scale={0.01}
      />
      <group position={[20.5, 4.64, 48.82]} rotation={[Math.PI, -0.15, Math.PI]} scale={2.65}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube041.geometry}
          material={materials['Building Base Color']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Roundcube041_1.geometry} material={materials['Material.001']} />
      </group>
      <group position={[9.95, 4.64, 48.95]} rotation={[-Math.PI, 0.02, -Math.PI]} scale={2.65}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube010.geometry}
          material={materials['Building Base Color']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Roundcube010_1.geometry} material={materials['Material.001']} />
      </group>
      <group position={[0.55, 4.79, 48.57]} rotation={[-Math.PI, 0.17, -Math.PI]} scale={2.65}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube011.geometry}
          material={materials['Building Base Color']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Roundcube011_1.geometry} material={materials['Material.001']} />
      </group>
      <group position={[21.57, 4.46, 29.14]} rotation={[0, -0.22, 0]} scale={2.65}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube012.geometry}
          material={materials['Building Base Color']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Roundcube012_1.geometry} material={materials['Material.001']} />
      </group>
      <group position={[12, 4.46, 28.95]} rotation={[0, -0.02, 0]} scale={2.65}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube013.geometry}
          material={materials['Building Base Color']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Roundcube013_1.geometry} material={materials['Material.001']} />
      </group>
      <group position={[1.52, 4.45, 29.4]} rotation={[0, 0.12, 0]} scale={2.65}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube015.geometry}
          material={materials['Building Base Color']}
        />
        <mesh castShadow receiveShadow geometry={nodes.Roundcube015_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.simple_tower.geometry}
        material={materials['simple tower']}
        position={[109.64, 9.93, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={11.03}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass.geometry}
        material={materials.Grass}
        position={[86.11, 0.32, 45.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.63, 0, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass2.geometry}
        material={materials.Grass2}
        position={[86.6, 0.32, 45.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.54, 0, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass3.geometry}
        material={materials.Grass3}
        position={[85.57, 0.32, 45.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.65, 0, 0.65]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass4.geometry}
        material={materials.Grass4}
        position={[85.23, 0.32, 45.38]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.33, 0, 0.33]}
      />
      <group position={[4.88, -0.03, 43.79]} scale={55.15}>
        <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials.Leaves} />
        <mesh castShadow receiveShadow geometry={nodes.Plane001_1.geometry} material={materials['Material.007']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials['Material.008']}
        position={[5.03, 0.32, 138.66]}
        scale={[97.99, 11.75, 59.22]}
      />*/}
    </group>
  );
}

useGLTF.preload('/ripple-demo-scene-v001-cleaned-12-22-22 v6.glb');
